In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\HP\Desktop\SQL\archive\sales_data_sample.csv", encoding='latin1')
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [5]:
df = df.drop_duplicates()
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [6]:
df = df.drop(columns = "ADDRESSLINE2")
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PHONE,ADDRESSLINE1,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,2125557818,897 Long Airport Avenue,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,26.47.1555,59 rue de l'Abbaye,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,6265557265,78934 Hillside Dr.,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,6505551386,7734 Strong St.,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,981-443655,Torikatu 38,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,61.77.6555,1 rue Alsace-Lorraine,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,6175559555,8616 Spinnaker Dr.,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [7]:
df = df.drop(columns = "STATE")
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,NaN,Yoshido,Juri,Medium

In [8]:
df = df.drop(columns = "TERRITORY")
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [9]:
df.rename(columns={ 'ORDERNUMBER': 'Order_Number'})

,Order_Number,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [10]:
df = df.rename(columns={ 'QUANTITYORDERED': 'Quantity_Ordered'})
df

,ORDERNUMBER,Quantity_Ordered,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [11]:
df = df.rename(columns={ 'PRICEEACH': 'Price_Each'})
df

,ORDERNUMBER,Quantity_Ordered,Price_Each,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [12]:
df = df.rename(columns={ 'ORDERLINENUMBER': 'Order_Line_Number',
                   'ORDERDATE': 'Order_Date',
                   'SALES': 'Sales',
                   'STATUS': 'Status',
                   'PRODUCTCODE': 'Product_Code',
                   'PHONE	': 'Phone',
                   'CITY': 'City',
                   'CONTACTLASTNAME': 'Last_Name',
                   'CONTACTFIRSTNAME': 'First_Name',
                   'DEALSIZE': 'Deal_Size'
})

df

,ORDERNUMBER,Quantity_Ordered,Price_Each,Order_Line_Number,Sales,Order_Date,Status,QTR_ID,MONTH_ID,YEAR_ID,...,Product_Code,CUSTOMERNAME,PHONE,ADDRESSLINE1,City,POSTALCODE,COUNTRY,Last_Name,First_Name,Deal_Size
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [13]:
df = df.rename(columns={ 'MONTH_ID': 'Month_ID',
                   'YEAR_ID	': 'Year_ID	',
                   'CUSTOMERNAME': 'Company_Name',
                   'PHONE': 'Phone',
                   'ADDRESSLINE1': 'Address',
                   'POSTALCODE	': 'Postal_Code',
                   'COUNTRY': 'Country'
})

df

,ORDERNUMBER,Quantity_Ordered,Price_Each,Order_Line_Number,Sales,Order_Date,Status,QTR_ID,Month_ID,YEAR_ID,...,Product_Code,Company_Name,Phone,Address,City,POSTALCODE,Country,Last_Name,First_Name,Deal_Size
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [14]:
df["Last_Name"] = df['Last_Name'].str.strip()
df

,ORDERNUMBER,Quantity_Ordered,Price_Each,Order_Line_Number,Sales,Order_Date,Status,QTR_ID,Month_ID,YEAR_ID,...,Product_Code,Company_Name,Phone,Address,City,POSTALCODE,Country,Last_Name,First_Name,Deal_Size
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [15]:
df['First_Name'] = df['First_Name'].str.strip()
df

,ORDERNUMBER,Quantity_Ordered,Price_Each,Order_Line_Number,Sales,Order_Date,Status,QTR_ID,Month_ID,YEAR_ID,...,Product_Code,Company_Name,Phone,Address,City,POSTALCODE,Country,Last_Name,First_Name,Deal_Size
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,S72_3212,Euro Shopping Channel,(91) 555 94 44,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61.77.6555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [16]:
df["Phone"] = df["Phone"].str.replace(r'[^0-9]'  , '', regex=True)
df

,ORDERNUMBER,Quantity_Ordered,Price_Each,Order_Line_Number,Sales,Order_Date,Status,QTR_ID,Month_ID,YEAR_ID,...,Product_Code,Company_Name,Phone,Address,City,POSTALCODE,Country,Last_Name,First_Name,Deal_Size
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26471555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,33146627555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,915559444,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,S72_3212,Euro Shopping Channel,915559444,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61776555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [17]:
df["POSTALCODE"] = df["POSTALCODE"].fillna(0)
df

,ORDERNUMBER,Quantity_Ordered,Price_Each,Order_Line_Number,Sales,Order_Date,Status,QTR_ID,Month_ID,YEAR_ID,...,Product_Code,Company_Name,Phone,Address,City,POSTALCODE,Country,Last_Name,First_Name,Deal_Size
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26471555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,33146627555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,0,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,915559444,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,S72_3212,Euro Shopping Channel,915559444,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61776555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [18]:
df.drop_duplicates(subset= ['Address'])
df

,ORDERNUMBER,Quantity_Ordered,Price_Each,Order_Line_Number,Sales,Order_Date,Status,QTR_ID,Month_ID,YEAR_ID,...,Product_Code,Company_Name,Phone,Address,City,POSTALCODE,Country,Last_Name,First_Name,Deal_Size
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 00:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,26471555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 00:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,33146627555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 00:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,0,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/02/2004 00:00,Shipped,4,12,2004,...,S72_3212,Euro Shopping Channel,915559444,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,S72_3212,"Oulu Toy Supplies, Inc.",981443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 00:00,Resolved,1,3,2005,...,S72_3212,Euro Shopping Channel,915559444,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,S72_3212,Alpha Cognac,61776555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 00:00,On Hold,2,5,2005,...,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [19]:
df= df.drop(columns=['Order_Line_Number', 'Month_ID', 'YEAR_ID' ])
df

,ORDERNUMBER,Quantity_Ordered,Price_Each,Sales,Order_Date,Status,QTR_ID,PRODUCTLINE,MSRP,Product_Code,Company_Name,Phone,Address,City,POSTALCODE,Country,Last_Name,First_Name,Deal_Size
0,10107,30,95.70,2871.00,2/24/2003 0:00,Shipped,1,Motorcycles,95,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,2765.90,05/07/2003 00:00,Shipped,2,Motorcycles,95,S10_1678,Reims Collectables,26471555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,3884.34,07/01/2003 00:00,Shipped,3,Motorcycles,95,S10_1678,Lyon Souveniers,33146627555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,3746.70,8/25/2003 0:00,Shipped,3,Motorcycles,95,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,5205.27,10/10/2003 00:00,Shipped,4,Motorcycles,95,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,0,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,2244.40,12/02/2004 00:00,Shipped,4,Ships,54,S72_3212,Euro Shopping Channel,915559444,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,3978.51,1/31/2005 0:00,Shipped,1,Ships,54,S72_3212,"Oulu Toy Supplies, Inc.",981443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,5417.57,03/01/2005 00:00,Resolved,1,Ships,54,S72_3212,Euro Shopping Channel,915559444,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,2116.16,3/28/2005 0:00,Shipped,1,Ships,54,S72_3212,Alpha Cognac,61776555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,3079.44,05/06/2005 00:00,On Hold,2,Ships,54,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [20]:
df = df.rename(columns={ 'ORDERNUMBER': 'Order_Number'})
df

,Order_Number,Quantity_Ordered,Price_Each,Sales,Order_Date,Status,QTR_ID,PRODUCTLINE,MSRP,Product_Code,Company_Name,Phone,Address,City,POSTALCODE,Country,Last_Name,First_Name,Deal_Size
0,10107,30,95.70,2871.00,2/24/2003 0:00,Shipped,1,Motorcycles,95,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,2765.90,05/07/2003 00:00,Shipped,2,Motorcycles,95,S10_1678,Reims Collectables,26471555,59 rue de l'Abbaye,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,3884.34,07/01/2003 00:00,Shipped,3,Motorcycles,95,S10_1678,Lyon Souveniers,33146627555,27 rue du Colonel Pierre Avia,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,3746.70,8/25/2003 0:00,Shipped,3,Motorcycles,95,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,5205.27,10/10/2003 00:00,Shipped,4,Motorcycles,95,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,San Francisco,0,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,2244.40,12/02/2004 00:00,Shipped,4,Ships,54,S72_3212,Euro Shopping Channel,915559444,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,3978.51,1/31/2005 0:00,Shipped,1,Ships,54,S72_3212,"Oulu Toy Supplies, Inc.",981443655,Torikatu 38,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,5417.57,03/01/2005 00:00,Resolved,1,Ships,54,S72_3212,Euro Shopping Channel,915559444,"C/ Moralzarzal, 86",Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,2116.16,3/28/2005 0:00,Shipped,1,Ships,54,S72_3212,Alpha Cognac,61776555,1 rue Alsace-Lorraine,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,3079.44,05/06/2005 00:00,On Hold,2,Ships,54,S72_3212,Gifts4AllAges.com,6175559555,8616 Spinnaker Dr.,Boston,51003,USA,Yoshido,Juri,Medium

In [39]:
df['Order_Date'] = pd.to_datetime(df['Order_Date']).dt.date
df['Order_Date']

0       2003-02-24
1       2003-05-07
2       2003-07-01
3       2003-08-25
4       2003-10-10
           ...
2818    2004-12-02
2819    2005-01-31
2820    2005-03-01
2821    2005-03-28
2822    2005-05-06
Name: Order_Date, Length: 2823, dtype: object

In [40]:
df

,Order_Number,Quantity_Ordered,Price_Each,Sales,Order_Date,Status,QTR_ID,PRODUCTLINE,Company_Name,City,Country,Deal_Size
0,10107,30,95.70,2871.00,2003-02-24,Shipped,1,Motorcycles,Land of Toys Inc.,NYC,USA,Small
1,10121,34,81.35,2765.90,2003-05-07,Shipped,2,Motorcycles,Reims Collectables,Reims,France,Small
2,10134,41,94.74,3884.34,2003-07-01,Shipped,3,Motorcycles,Lyon Souveniers,Paris,France,Medium
3,10145,45,83.26,3746.70,2003-08-25,Shipped,3,Motorcycles,Toys4GrownUps.com,Pasadena,USA,Medium
4,10159,49,100.00,5205.27,2003-10-10,Shipped,4,Motorcycles,Corporate Gift Ideas Co.,San Francisco,USA,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,2244.40,2004-12-02,Shipped,4,Ships,Euro Shopping Channel,Madrid,Spain,Small
2819,10373,29,100.00,3978.51,2005-01-31,Shipped,1,Ships,"Oulu Toy Supplies, Inc.",Oulu,Finland,Medium
2820,10386,43,100.00,5417.57,2005-03-01,Resolved,1,Ships,Euro Shopping Channel,Madrid,Spain,Medium
2821,10397,34,62.24,2116.16,2005-03-28,Shipped,1,Ships,Alpha Cognac,Toulouse,France,Small
2822,10414,47,65.52,3079.44,2005-05-06,On Hold,2,Ships,Gifts4AllAges.com,Boston,USA,Medium

In [57]:
df = df.drop(columns=['Phone', 'Address','POSTALCODE','Last_Name', 'First_Name', 'MSRP', 'Product_Code'])
df

KeyError: "['Phone', 'Address', 'POSTALCODE', 'Last_Name', 'First_Name', 'MSRP', 'Product_Code'] not found in axis"

In [56]:
df

,Order_Number,Quantity_Ordered,Price_Each,Sales,Order_Date,Status,QTR_ID,PRODUCTLINE,Company_Name,City,Country,Deal_Size
0,10107,30,95.70,2871.00,2003-02-24,Shipped,1,Motorcycles,Land of Toys Inc.,NYC,USA,Small
1,10121,34,81.35,2765.90,2003-05-07,Shipped,2,Motorcycles,Reims Collectables,Reims,France,Small
2,10134,41,94.74,3884.34,2003-07-01,Shipped,3,Motorcycles,Lyon Souveniers,Paris,France,Medium
3,10145,45,83.26,3746.70,2003-08-25,Shipped,3,Motorcycles,Toys4GrownUps.com,Pasadena,USA,Medium
4,10159,49,100.00,5205.27,2003-10-10,Shipped,4,Motorcycles,Corporate Gift Ideas Co.,San Francisco,USA,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,2244.40,2004-12-02,Shipped,4,Ships,Euro Shopping Channel,Madrid,Spain,Small
2819,10373,29,100.00,3978.51,2005-01-31,Shipped,1,Ships,"Oulu Toy Supplies, Inc.",Oulu,Finland,Medium
2820,10386,43,100.00,5417.57,2005-03-01,Resolved,1,Ships,Euro Shopping Channel,Madrid,Spain,Medium
2821,10397,34,62.24,2116.16,2005-03-28,Shipped,1,Ships,Alpha Cognac,Toulouse,France,Small
2822,10414,47,65.52,3079.44,2005-05-06,On Hold,2,Ships,Gifts4AllAges.com,Boston,USA,Medium

In [58]:
print(df.columns.tolist())

['Order_Number', 'Quantity_Ordered', 'Price_Each', 'Sales', 'Order_Date', 'Status', 'QTR_ID', 'PRODUCTLINE', 'Company_Name', 'City', 'Country', 'Deal_Size']

In [42]:
##  Month with the highest sales

monthly_sales = df.groupby('QTR_ID')['Sales'].sum().sort_values(ascending=False)
print(monthly_sales)

QTR_ID
4    3874780.01
1    2350817.73
2    2048120.30
3    1758910.81
Name: Sales, dtype: float64

In [43]:
##  The country that made the most revenue

country_sales = df.groupby('Country')['Sales'].sum().sort_values(ascending=False)
print(country_sales)

Country
USA            3627982.83
Spain          1215686.92
France         1110916.52
Australia       630623.10
UK              478880.46
Italy           374674.31
Finland         329581.91
Norway          307463.70
Singapore       288488.41
Denmark         245637.15
Canada          224078.56
Germany         220472.09
Sweden          210014.21
Austria         202062.53
Japan           188167.81
Switzerland     117713.56
Belgium         108412.62
Philippines      94015.73
Ireland          57756.43
Name: Sales, dtype: float64

In [44]:
## Product line which sold the most

product_sales = df.groupby('PRODUCTLINE')['Sales'].sum().sort_values(ascending=False)
print(product_sales)

PRODUCTLINE
Classic Cars        3919615.66
Vintage Cars        1903150.84
Motorcycles         1166388.34
Trucks and Buses    1127789.84
Planes               975003.57
Ships                714437.13
Trains               226243.47
Name: Sales, dtype: float64

In [45]:
## Top 10 customers

top_customers = df.groupby('Company_Name')['Sales'].sum().sort_values(ascending=False).head(10)
print(top_customers)

Company_Name
Euro Shopping Channel           912294.11
Mini Gifts Distributors Ltd.    654858.06
Australian Collectors, Co.      200995.41
Muscle Machine Inc              197736.94
La Rochelle Gifts               180124.90
Dragon Souveniers, Ltd.         172989.68
Land of Toys Inc.               164069.44
The Sharp Gifts Warehouse       160010.27
AV Stores, Co.                  157807.81
Anna's Decorations, Ltd         153996.13
Name: Sales, dtype: float64

In [46]:
## Which deal size brings most revenue

deal_sales = df.groupby('Deal_Size')['Sales'].sum().sort_values(ascending=False)
print(deal_sales)

Deal_Size
Medium    6087432.24
Small     2643077.35
Large     1302119.26
Name: Sales, dtype: float64

In [47]:
##  Best performing quarter

quarter_sales = df.groupby('QTR_ID')['Sales'].sum().sort_values(ascending=False)
print(quarter_sales)

QTR_ID
4    3874780.01
1    2350817.73
2    2048120.30
3    1758910.81
Name: Sales, dtype: float64

In [48]:
## Total overall revenue

total_revenue = df['Sales'].sum()
print(f'Total Revenue: ${total_revenue:,.2f}')

Total Revenue: $10,032,628.85

In [49]:
## Total number of orders

total_orders = df['Order_Number'].count()
print(f'Total Orders: {total_orders}')

Total Orders: 2823

In [50]:
## Average sales per order

avg_sales = df['Sales'].mean()
print(f'Average Sales Per Order: ${avg_sales:,.2f}')

Average Sales Per Order: $3,553.89

In [51]:
## Best performing city

city_sales = df.groupby('City')['Sales'].sum().sort_values(ascending=False).head(10)
print(city_sales)

City
Madrid           1082551.44
San Rafael        654858.06
NYC               560787.77
Singapore         288488.41
Paris             268944.68
San Francisco     224358.68
New Bedford       207874.86
Nantes            204304.86
Melbourne         200995.41
Brickhaven        165255.20
Name: Sales, dtype: float64

In [52]:
## Order status breakdown

status_count = df['Status'].value_counts()
print(status_count)

Status
Shipped       2617
Cancelled       60
Resolved        47
On Hold         44
In Process      41
Disputed        14
Name: count, dtype: int64

In [53]:
df.to_csv('sales_cleaned.csv', index=False)

In [59]:
import os
print(os.getcwd())

C:\Users\HP

In [60]:
import os
print(os.getcwd())

C:\Users\HP